### ISSUE TITLE
cmake build fails on ubuntu 18.04 with qt5-default

### ISSUE THREAD

**Issue by Nine-H** [PSI-Rockin/DobieStation#203]
I wanted to test this on my laptop, but building master failed with the following error:

```
[ 93%] Building CXX object CMakeFiles/DobieStation.dir/src/qt/gamelistwidget.cpp.o
/home/nine/Projects/DobieStation/src/qt/gamelistwidget.cpp: In member function ‘virtual QVariant GameListModel::data(const QModelIndex&, int) const’:
/home/nine/Projects/DobieStation/src/qt/gamelistwidget.cpp:48:30: error: ‘class QLocale’ has no member named ‘formattedDataSize’
             return QLocale().formattedDataSize(file_info.size());
                              ^~~~~~~~~~~~~~~~~
CMakeFiles/DobieStation.dir/build.make:1646: recipe for target 'CMakeFiles/DobieStation.dir/src/qt/gamelistwidget.cpp.o' failed
make[2]: *** [CMakeFiles/DobieStation.dir/src/qt/gamelistwidget.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/DobieStation.dir/all' failed
make[1]: *** [CMakeFiles/DobieStation.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

possibly my f-up (apologies in advance).

**Comment by tadanokojin** [comment]
You need QT 5.10 at least.

**Comment by Nine-H** [comment]
yeah and this is a dupe soz.

**Comment by TuxThePenguin0** [comment]
Can confirm it builds fine with cmake on Ubuntu 18.10
